#!/usr/bin/env python
import os

from confu import aws, ansible


region = os.environ.get('AWS_REGION', 'us-east-1')
aws.cxn.activate(profile_name='poundpay', default_region=region)

inventory = ansible.AWSRemoteInventory(
    instances=(
        aws.instances()
        .regions(region)
        .filter(('tag:confu:infra-silo', 'zookeeper'))
        .filter(('instance-state-name', 'running'))
    ),
    group_tags=[
       'aws:cloudformation:stack-name',
       'confu:infra-silo',
       ('confu:infra-env', 'env-{value}', 'infra_env'),
       ('confu:roles', lambda value: value.split(','))
    ],
)

if __name__ == '__main__':
    inventory.cli()
