#!/usr/bin/env python

from confu import aws, ansible


aws.cxn.activate(default_region='this')

inventory = ansible.AWSLocalInventory(
    group_tags=[
       'aws:cloudformation:stack-name',
       'confu:infra-silo',
       ('confu:infra-env', 'env-{value}', 'infra_env'),
       ('confu:app-env', 'env-{value}', 'app_env'),
       ('confu:roles', lambda value: value.split(','))
    ],
)

if __name__ == '__main__':
    inventory.cli()
